# Generated by Django 5.1.6 on 2025-08-24 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chat_config', '0003_chat_source_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField()),
                ('result_txt', models.TextField(blank=True, null=True)),
                ('result_img', models.URLField(blank=True, max_length=1000, null=True)),
                ('generated_code', models.TextField()),
                ('chat_id', models.ForeignKey(db_column='chat_id', on_delete=django.db.models.deletion.CASCADE, related_name='prompts', to='chat_config.chat')),
            ],
        ),
    ]
