version: '3.8'

services:
  backend:
    build: ./main-backend-service
    ports:
      - "8000:8000"
    volumes:
      - ./main-backend-service:/app
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - PYTHONUNBUFFERED=1
    restart: always

  proxy:
    build: ./proxy-orchestration-server
    ports:
      - "8001:8001"
    volumes:
      - ./proxy-orchestration-server:/app
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - backend
    restart: always

  auth:
    build: ./auth-service
    ports:
      - "3001:3001"
    volumes:
      - ./auth-service:/usr/src/app
      - /usr/src/app/node_modules
    restart: always

  frontend:
    build: ../Axnos-UI
    ports:
      - "3000:3000"
    volumes:
      - ../Axnos-UI:/app
      - /app/node_modules
      - /app/.next
    depends_on:
      - proxy
      - auth
    restart: always
