# Generated by Django 5.0.6 on 2025-08-19 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default=uuid.uuid4, max_length=255)),
                ('user_id', models.IntegerField()),
                ('dataset', models.URLField(max_length=5000)),
                ('created_At', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
