# Generated by Django 5.0.6 on 2025-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_config', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='name_generated',
            field=models.BooleanField(default=False),
        ),
    ]
