# Generated by Django 5.2.5 on 2025-08-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_config', '0002_chat_name_generated'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='source_type',
            field=models.CharField(choices=[('file', 'File'), ('database_url', 'Database URL')], default='file', max_length=20),
        ),
    ]
