# Generated by Django 5.2.7 on 2025-12-13 05:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_config', '0004_alter_chat_dataset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='user_id',
            field=models.CharField(default=uuid.uuid4, max_length=255),
        ),
    ]
