# Generated by Django 5.2.7 on 2026-03-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_config', '0005_alter_chat_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='preview',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
