# Generated by Django 5.2.7 on 2026-03-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat_config', '0006_chat_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='table_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
